In [2]:
import random as rd
rd.seed(0)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
raw_data = pd.read_csv('titanic.csv')
raw_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
raw_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
raw_data.drop(columns=['Cabin'], inplace = True)

In [11]:
#mean vs median to fill missing ages
print(raw_data.Age.mean())
print(raw_data.Age.median())

29.69911764705882
28.0


In [17]:
raw_data.Age.fillna(raw_data.Age.median(),inplace = True)

In [18]:
raw_data.Embarked.mode()[0]

'S'

In [21]:
raw_data.Embarked.fillna(raw_data.Embarked.mode()[0], inplace = True)

In [24]:
raw_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [27]:
raw_data


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked  
0        0         A/5 21171   7.2500        S  
1        0          PC 17599  71.2833        C  
2        0  STON/O2. 3101282   7.9250        S  
3        0            113803  53.1000        S  
4        0            373450   8.0500        S  
..     ...               ...      ...      ...  
886      0            211536  13.0000        S  
887      0            112053  30.0000        S  
888      2        W./C. 6607  23.4500        S  
889      0            111369  30.0000        C  
890      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [42]:
#saving the data after preprocessing
raw_data.to_csv('finaltitanic.csv', index=None)

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
preprocessed_data = pd.read_csv('finaltitanic.csv')
preprocessed_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked  
0        0         A/5 21171   7.2500        S  
1        0          PC 17599  71.2833        C  
2        0  STON/O2. 3101282   7.9250        S  
3        0            113803  53.1000        S  
4        0            373450   8.0500        S  
..     ...               ...      ...      ...  
886      0            211536  13.0000        S  
887      0            112053  30.0000        S  
888      2        W./C. 6607  23.4500        S  
889      0            111369  30.0000        C  
890      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [44]:
preprocessed_data["Sex"] = (preprocessed_data["Sex"] == "male").astype(int)

In [45]:
preprocessed_data["Sex"].unique()

array([1, 0])

In [46]:
preprocessed_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

In [48]:
preprocessed_data["Pclass"] = (preprocessed_data["Pclass"]).astype(int)

In [49]:
preprocessed_data["Pclass"].unique()

array([3, 1, 2])

In [58]:
encoder = OneHotEncoder()
ed = encoder.fit_transform(preprocessed_data[["Embarked"]]).toarray()
ed = pd.DataFrame(ed,columns=encoder.get_feature_names_out())
preprocessed_data = pd.concat([preprocessed_data, ed],axis = 1)

In [61]:
preprocessed_data.drop(columns=['Embarked'], inplace = True)

In [63]:
preprocessed_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  Embarked_C  Embarked_Q  Embarked_S  
0         A/5 21171   7.2500         0.0         0.0         1.0  
1          PC 17599  71.2833         1.0         0.0         0.0  
2  STON/O2. 3101282   7.9250         0.0         0.0         1.0  
3            113803  53.1000         0.0         0.0         1.0  
4            373450   8.0500         0.0         0.0         1.0

In [66]:
preprocessed_data.drop(columns=['PassengerId','Ticket','Name'], inplace = True)

In [68]:
preprocessed_data.head(10)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    1  22.0      1      0   7.2500         0.0         0.0   
1         1       1    0  38.0      1      0  71.2833         1.0         0.0   
2         1       3    0  26.0      0      0   7.9250         0.0         0.0   
3         1       1    0  35.0      1      0  53.1000         0.0         0.0   
4         0       3    1  35.0      0      0   8.0500         0.0         0.0   
5         0       3    1  28.0      0      0   8.4583         0.0         1.0   
6         0       1    1  54.0      0      0  51.8625         0.0         0.0   
7         0       3    1   2.0      3      1  21.0750         0.0         0.0   
8         1       3    0  27.0      0      2  11.1333         0.0         0.0   
9         1       2    0  14.0      1      0  30.0708         1.0         0.0   

   Embarked_S  
0         1.0  
1         0.0  
2         1.0  
3         1.0  
4         1.0  
5         0.0  
6         1.0  
7         1.0  
8         1.0  
9         0.0

In [69]:
#saving data 
preprocessed_data.to_csv('modeldata.csv', index = None)

In [71]:
data = pd.read_csv('modeldata.csv')
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    1  22.0      1      0   7.2500         0.0         0.0   
1         1       1    0  38.0      1      0  71.2833         1.0         0.0   
2         1       3    0  26.0      0      0   7.9250         0.0         0.0   
3         1       1    0  35.0      1      0  53.1000         0.0         0.0   
4         0       3    1  35.0      0      0   8.0500         0.0         0.0   

   Embarked_S  
0         1.0  
1         0.0  
2         1.0  
3         1.0  
4         1.0

In [73]:
#features and labels (x and y)
X = data.drop(columns=['Survived'], axis = 1)
Y = data['Survived']

In [74]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_validation_test, Y_train, Y_validation_test = train_test_split(X,Y , test_size=0.4, random_state=100)

In [78]:
X_validation, X_test, Y_validation, Y_test =train_test_split(X,Y , test_size=0.5, random_state=100)

In [82]:
print(len(X_train))
print(len(X_validation))
print(len(X_test))
print(len(Y_train))
print(len(Y_validation))
print(len(Y_test))

534
445
446
534
445
446


In [ ]:
#Logistic regression (perceptron)
#Decision tree
#Support vector machine (SVM)
#RandomForestClassifier
#GradientBoostingClassifier
#AdaBoostClassifier

In [83]:
# Train logistic regression model
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model .fit(X_train,Y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [84]:
# Train decision tree model ; don't use any hyperparameter
from sklearn.tree import DecisionTreeClassifier

dt_model =DecisionTreeClassifier()
dt_model .fit(X_train,Y_train)

DecisionTreeClassifier()

In [85]:
# Train SVM model ; don't use any hyperparameter
from sklearn.svm import SVC

svm_model =SVC()
svm_model.fit(X_train,Y_train)

SVC()

In [86]:
# Train random forest model ; don't use any hyperparameter
from sklearn.ensemble import RandomForestClassifier

rf_model =RandomForestClassifier()
rf_model.fit(X_train,Y_train)

RandomForestClassifier()

In [87]:
# Train gradient boosting model ; don't use any hyperparameter
from sklearn.ensemble import GradientBoostingClassifier

gb_model =GradientBoostingClassifier()
gb_model.fit(X_train,Y_train)

GradientBoostingClassifier()

In [88]:
# Train Adaboost model ; don't use any hyperparameter
from sklearn.ensemble import AdaBoostClassifier

ab_model =AdaBoostClassifier()
ab_model.fit(X_train,Y_train)

AdaBoostClassifier()

In [89]:
# print accuracy of each model on validation data
print("Scores of the models")
print("Logistic regression:",lr_model.score(X_validation,Y_validation) )
print("Decision tree:",dt_model.score(X_validation,Y_validation)  )
print("SVM:", svm_model.score(X_validation,Y_validation) )
print("Random forest:",rf_model.score(X_validation,Y_validation)  )
print("Gradient boosting:",gb_model.score(X_validation,Y_validation)  )
print("AdaBoost:",ab_model.score(X_validation,Y_validation)  )

Scores of the models
Logistic regression: 0.8292134831460675
Decision tree: 0.9865168539325843
SVM: 0.6696629213483146
Random forest: 0.9865168539325843
Gradient boosting: 0.9213483146067416
AdaBoost: 0.8449438202247191


In [100]:
# print F1-score of each model on validation data
from sklearn.metrics import f1_score

print("F1-scores of the models:")
lr_pred_labels =lr_model.predict(X_validation)
print("Logistic regression:", f1_score(Y_validation,lr_pred_labels))
dt_pred_labels =dt_model.predict(X_validation)
print("Decision tree:",f1_score(Y_validation,dt_pred_labels) )
svm_pred_labels =svm_model.predict(X_validation)
print("SVM:",f1_score(Y_validation,svm_pred_labels) )
rf_pred_labels =rf_model.predict(X_validation)
print("Random forest:",f1_score(Y_validation,rf_pred_labels) )
gb_pred_labels =gb_model.predict(X_validation)
print("Gradient boosting:",f1_score(Y_validation,gb_pred_labels) )
ab_pred_labels =ab_model.predict(X_validation)
print("AdaBoost:", f1_score(Y_validation,ab_pred_labels))

F1-scores of the models:
Logistic regression: 0.7466666666666666
Decision tree: 0.9806451612903226
SVM: 0.3466666666666667
Random forest: 0.9806451612903226
Gradient boosting: 0.8844884488448844
AdaBoost: 0.7676767676767676


In [135]:
Y_pred = gb_model.predict(X_test)

In [102]:
from sklearn.metrics import classification_report

In [136]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.86       262
           1       0.82      0.73      0.77       184

    accuracy                           0.82       446
   macro avg       0.82      0.81      0.81       446
weighted avg       0.82      0.82      0.82       446



In [108]:
# print accuracy of random forest model on testing data
print("Random Forest:",rf_model.score(X_test,Y_test))

Random Forest: 0.8430493273542601


In [115]:
gb_pred_labels =gb_model.predict(X_test)
print("Gradient boosting:",f1_score(Y_test,gb_pred_labels) )
rf_pred_labels =rf_model.predict(X_test)
print("Random forest:",f1_score(Y_test,rf_pred_labels) )
dt_pred_labels =dt_model.predict(X_test)
print("Decision tree:",f1_score(Y_test,dt_pred_labels) )

Gradient boosting: 0.7723342939481268
Random forest: 0.8022598870056498
Decision tree: 0.7734806629834255


In [137]:
Y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,

In [130]:
np.array(Y_test)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,